StationaryManagment/Models/sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int id { get; set; }
        public string sale_product { get; set; }
        public string sale_quantity { get; set; }
        public System.DateTime sale_date { get; set; }
    }
}

StationaryManagment/Controllers/SaleController.cs
using GroceryManagment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroceryManagment.Controllers
{
    public class SaleController : Controller
    {
        Grocery_managementEntities db = new Grocery_managementEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplaySale()
        {
            List<sale> list = db.sales.OrderByDescending(x => x.id).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult SaleProduct()
        {
            // Create a new instance of the purchase model
            var saleModel = new sale();

            // Get a list of product names
            List<string> productList = db.products.Select(x => x.product_name).ToList();

            // Set the SelectList for the dropdown
            ViewBag.ProductName = new SelectList(productList);

            // Pass the purchaseModel to the view
            return View(saleModel);
        }


        [HttpPost]
        public ActionResult saleProduct(sale s)
        {
            db.sales.Add(s);

            string product_name = s.sale_product;

            product prd = db.products.FirstOrDefault(p => p.product_name == product_name);
            prd.product_quantity = Convert.ToString(Convert.ToInt32(prd.product_quantity) - Convert.ToInt32(s.sale_quantity));

            db.SaveChanges();

            return RedirectToAction("Displaysale");
        }


        [HttpGet]
        public ActionResult Details(int id)
        {

            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            return View(s);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            return View(s);
        }

        [HttpPost]
        public ActionResult Delete(int id, sale sa)
        {

            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            if (s != null)
            {
                db.sales.Remove(s);
                db.SaveChanges();
            }
            return RedirectToAction("DisplaySale");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            List<string> list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(s);
        }

        [HttpPost]
        public ActionResult Edit(int id, sale sa)
        {
            sale s = db.sales.Where(x => x.id == id).SingleOrDefault();
            s.sale_date = sa.sale_date;
            s.sale_product = sa.sale_product;
            s.sale_quantity = sa.sale_quantity;
            db.SaveChanges();
            return RedirectToAction("Displaysale");
        }
    }
}

StationaryManagment/Views/Sale/Delete.cshtml
@model GroceryManagment.Models.sale

@{
    ViewBag.Title = "Delete";
}

<style>
    body{
        background-color: lightcyan;
    }
</style>

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Product Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_product)
        </dd>

        <dt>
            @Html.DisplayName("Product Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_quantity)
        </dd>

        <dt>
            @Html.DisplayName("Sale Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-outline-primary" /> |
            @Html.ActionLink("cancel", "DisplaySale", "sale", new { @class = "btn btn-outline-danger" })
        </div>
    }
</div>

StationaryManagment/Views/Sale/Details.cshtml
@model GroceryManagment.Models.sale

@{
    ViewBag.Title = "Details";
}

<style>

    body{
        background-color: lightcyan;
    }
    .container{
        text-align: center;
        margin-left: 20px;
    }
    </style>
<div class="container">
<h2>Details</h2>

<div>
    <h4>sale</h4>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Product Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_product)
        </dd>

        <dt>
            @Html.DisplayName("Product Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_quantity)
        </dd>

        <dt>
            @Html.DisplayName("Sale Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sale_date)
        </dd>

    </dl>
</div>
<br>
<p>
    @Html.ActionLink("Edit", "Edit", "sale", new { id = Model.id }, new { @class = "btn btn-outline-primary" }) 
    @Html.ActionLink("cancel", "DisplaySale", "sale", new { @class = "btn btn-outline-danger" })
</p>
     </div>

StationaryManagment/Views/Sale/DisplaySale.cshtml
@model IEnumerable<GroceryManagment.Models.sale>

@{
    ViewBag.Title = "DisplaySale";
}

<style>
    /* Custom CSS for enhanced styling */
    body {
        background-color: lightcyan;
        /*background-image: url('~/Content/themes/base/images/photo-1568871391149-449702439177.jpg');*/
    }

    h2 {
        color: #333;
        font-size: 28px;
        margin-bottom: 20px;
    }

    .btn-primary,
    .btn-success,
    .btn-danger {
        margin-right: 5px;
    }

    .table-responsive {
        border: 1px solid #ddd;
        padding: 15px;
        border-radius: 5px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
        }

    .thead-dark th {
        background-color: #333;
        color: white;
    }

    /* Custom CSS for table hover effect */
    .table tr:hover {
        background-color: #f5f5f5;
    }
</style>

<script>
    // JavaScript for confirming delete action
    function confirmDelete(id) {
        if (confirm("Are you sure you want to delete this sale record?")) {
            window.location.href = '@Url.Action("Delete", "Sale", new { id = "__id__" })'.replace('__id__', id);
        }
    }
</script>

<div class="container mt-5">
    <h2>Display Sell Items</h2>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayName("Product Name")</th>
                    <th>@Html.DisplayName("Product Quantity")</th>
                    <th>@Html.DisplayName("Sale Date")</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.sale_product)</td>
                        <td>@Html.DisplayFor(modelItem => item.sale_quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.sale_date)</td>
                        <td>
                            <button class="btn btn-outline-primary btn-sm" onclick="location.href='@Url.Action("Edit", "Sale", new { id = item.id })'">Edit</button>
                            <button class="btn btn-outline-success btn-sm" onclick="location.href='@Url.Action("Details", "Sale", new { id = item.id })'">Details</button>
                            <button class="btn btn-outline-danger btn-sm" onclick="confirmDelete(@item.id)">Delete</button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <p>
        @Html.ActionLink("Sell Item", "SaleProduct", "sale", new { @class = "btn btn-primary px-2 py-2 mt-3" })
    </p>
</div>

StationaryManagment/Views/Sale/Edit.cshtml
@model GroceryManagment.Models.sale

@{
    ViewBag.Title = "Edit";
}

<style>
    /* Custom CSS styles */
    body{
        background-color: lightcyan;
    }

    .form-horizontal {
        max-width: 600px;
        margin: 0 auto;
    }

    .control-label {
        font-weight: bold;
    }

    .form-control {
        border: 2px solid #ccc;
        padding: 8px;
        border-radius: 4px;
        width: 100%;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
    }

    .btn-danger {
        background-color: #dc3545;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 4px;
        cursor: pointer;
    }

    .text-danger {
        color: #dc3545;
    }
</style>


@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormat: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update sale Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.sale_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Item Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Sale Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_date, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.sale_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 my-3">
                <input type="submit" value="Update" class="btn btn-outline-primary" />
                @Html.ActionLink("Cancel", "DisplaySale", "sale", new { }, new { @class = "btn btn-outline-danger" })
            </div>
        </div>
    </div>
}

StationaryManagment/Views/Sale/SaleProduct.cshtml
@model GroceryManagment.Models.sale

@{
    ViewBag.Title = "SaleProduct";
}

<style>
    body{
        background-color: lightcyan
    }
    
</style>


<h2>Sell Item</h2>

@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormate: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sell</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Item Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.sale_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Sale Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sale_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sale_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 my-3">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplaySale", "sale", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}