StationaryManagment/Models/purchase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int id { get; set; }
        public string purchase_product { get; set; }
        public string purchase_quantity { get; set; }
        public System.DateTime purchase_date { get; set; }
    }
}

StationaryManagment/Controllers/PurchaseController.cs
using GroceryManagment.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GroceryManagment.Controllers
{
    public class PurchaseController : Controller
    {
        Grocery_managementEntities db = new Grocery_managementEntities();

        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<purchase> list = db.purchases.OrderByDescending(x => x.id).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            // Create a new instance of the purchase model
            var purchaseModel = new purchase();

            // Get a list of product names
            List<string> productList = db.products.Select(x => x.product_name).ToList();
            

            // Set the SelectList for the dropdown
            ViewBag.ProductName = new SelectList(productList);

            // Pass the purchaseModel to the view
            return View(purchaseModel);
        }


        [HttpPost]
        public ActionResult PurchaseProduct(purchase pur)
        {   
            db.purchases.Add(pur);
            string product_name = pur.purchase_product;
            
            product prd = db.products.FirstOrDefault(p => p.product_name == product_name);
            prd.product_quantity = Convert.ToString(Convert.ToInt32(prd.product_quantity) + Convert.ToInt32(pur.purchase_quantity));

            db.SaveChanges();
            
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            
            purchase p = db.purchases.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            purchase p = db.purchases.Where(x => x.id == id).SingleOrDefault();
            return View(p);
        }

        [HttpPost]
        public ActionResult Delete(int id, purchase per)
        {

            purchase p = db.purchases.Where(x => x.id == id).SingleOrDefault();
            if (p != null)
            {
                db.purchases.Remove(p);
                db.SaveChanges();
            }
            return RedirectToAction("DisplayPurchase");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            purchase p = db.purchases.Where(x => x.id == id).SingleOrDefault();
            List<string>list = db.products.Select(x => x.product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p);
        }

        [HttpPost]
        public ActionResult Edit(int id,purchase pur)
        {
            purchase p = db.purchases.Where(x => x.id == id).SingleOrDefault();
            p.purchase_date = pur.purchase_date;
            p.purchase_product = pur.purchase_product;
            p.purchase_quantity = pur.purchase_quantity;
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }

    }
}

StationaryManagment/Views/Purchase/Delete.cshtml
@model GroceryManagment.Models.purchase

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Purchase Product")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_product)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_quantity)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("cancel", "DisplayPurchase", "purchase", new { @class = "btn btn-danger" })
        </div>
    }
</div>

StationaryManagment/Views/Purchase/Details.cshtml
@model GroceryManagment.Models.purchase

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Purchase Product")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_product)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Quantity")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_quantity)
        </dd>

        <dt>
            @Html.DisplayName("Purchase Date")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.purchase_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit","purchase", new { id = Model.id }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("cancel", "DisplayPurchase","purchase", new { @class = "btn btn-danger" })
</p>

StationaryManagment/Views/Purchase/DisplayPurchase.cshtml
@model IEnumerable<GroceryManagment.Models.purchase>

@{
    ViewBag.Title = "DisplayPurchase";
}

<style>
    /* Custom CSS for enhanced styling */
    h2 {
        color: #333;
        font-size: 28px;
        margin-bottom: 20px;
    }

    .btn-primary,
    .btn-success,
    .btn-danger {
        margin-right: 5px;
    }

    .table-responsive {
        border: 1px solid #ddd;
        padding: 15px;
        border-radius: 5px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
    }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: center;
        }

    .thead-dark th {
        background-color: #333;
        color: white;
    }
</style>

<div class="container">
    <h2>Display Purchase</h2>
    <p>
        @Html.ActionLink("Create New", "PurchaseProduct", "purchase", new { @class = "btn btn-primary" })
    </p>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>@Html.DisplayName("Purchase Product")</th>
                    <th>@Html.DisplayName("Purchase Quantity")</th>
                    <th>@Html.DisplayName("Purchase Date")</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.purchase_product)</td>
                        <td>@Html.DisplayFor(modelItem => item.purchase_quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.purchase_date)</td>
                        <td>
                            <a href="@Url.Action("Edit", "Purchase", new { id = item.id })" class="btn btn-primary btn-sm">Edit</a>
                            <a href="@Url.Action("Details", "Purchase", new { id = item.id })" class="btn btn-success btn-sm">Details</a>
                            <a href="@Url.Action("Delete", "Purchase", new { id = item.id })" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

StationaryManagment/Views/Purchase/Edit.cshtml
@model GroceryManagment.Models.purchase

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormate: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update purchase Record</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Purchase Product", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.purchase_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.purchase_quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Purchase_Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.purchase_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.purchase_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 my-3">
                <input type="submit" value="Update" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}

StationaryManagment/Views/Purchase/PurchaseProduct.cshtml
@model GroceryManagment.Models.purchase

@{
    ViewBag.Title = "PurchaseProduct";
}

<h2>PurchaseProduct</h2>


@section Scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.13.2.min.js"></script>
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                dateFormate: "dd/M/yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
            });
        });
    </script>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>purchase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Purchase Product", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.purchase_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.purchase_product, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Purchase Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.purchase_quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.purchase_quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Purchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.purchase_date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.purchase_date, "", new { @class = "text-danger" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 my-3">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Cancel", "DisplayPurchase", "purchase", new { }, new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
}